Pref.connection.execute("TRUNCATE TABLE prefs;")
# 追加するデータを記載する
prefs = [
  {pic_no:1, region_no: 1, pref_name: "北海道"},
  {pic_no:2, region_no: 1, pref_name: "青森県"},
  {pic_no:3, region_no: 1, pref_name: "秋田県"},
  {pic_no:4, region_no: 1, pref_name: "岩手県"},
  {pic_no:5, region_no: 1, pref_name: "山形県"},
  {pic_no:6, region_no: 1, pref_name: "宮城県"},
  {pic_no:7, region_no: 1, pref_name: "福島県"},
  {pic_no:8, region_no: 1, pref_name: "千葉県"},
  {pic_no:9, region_no: 1, pref_name: "埼玉県"},
  {pic_no:10, region_no: 1, pref_name: "群馬県"},
  {pic_no:11, region_no: 1, pref_name: "栃木県"},
  {pic_no:12, region_no: 1, pref_name: "茨城県"},
  {pic_no:13, region_no: 1, pref_name: "神奈川県"},
  {pic_no:14, region_no: 1, pref_name: "東京都"},
  {pic_no:15, region_no: 1, pref_name: "山梨県"},
  {pic_no:16, region_no: 1, pref_name: "長野県"},
  {pic_no:17, region_no: 1, pref_name: "新潟県"},
  {pic_no:18, region_no: 1, pref_name: "富山県"},
  {pic_no:19, region_no: 1, pref_name: "石川県"},
  {pic_no:20, region_no: 1, pref_name: "福井県"},
  {pic_no:21, region_no: 1, pref_name: "静岡県"},
  {pic_no:22, region_no: 1, pref_name: "愛知県"},
  {pic_no:23, region_no: 1, pref_name: "三重県"},
  {pic_no:24, region_no: 1, pref_name: "岐阜県"},
  {pic_no:25, region_no: 2, pref_name: "大阪府"},
  {pic_no:26, region_no: 2, pref_name: "京都府"},
  {pic_no:27, region_no: 2, pref_name: "奈良県"},
  {pic_no:28, region_no: 2, pref_name: "兵庫県"},
  {pic_no:29, region_no: 2, pref_name: "滋賀県"},
  {pic_no:30, region_no: 2, pref_name: "和歌山県"},
  {pic_no:31, region_no: 2, pref_name: "鳥取県"},
  {pic_no:32, region_no: 2, pref_name: "岡山県"},
  {pic_no:33, region_no: 2, pref_name: "島根県"},
  {pic_no:34, region_no: 2, pref_name: "広島県"},
  {pic_no:35, region_no: 2, pref_name: "山口県"},
  {pic_no:36, region_no: 2, pref_name: "愛媛県"},
  {pic_no:37, region_no: 2, pref_name: "香川県"},
  {pic_no:38, region_no: 2, pref_name: "高知県"},
  {pic_no:39, region_no: 2, pref_name: "徳島県"},
  {pic_no:40, region_no: 2, pref_name: "福岡県"},
  {pic_no:41, region_no: 2, pref_name: "鹿児島県"},
  {pic_no:42, region_no: 2, pref_name: "熊本県"},
  {pic_no:43, region_no: 2, pref_name: "宮崎県"},
  {pic_no:44, region_no: 2, pref_name: "長崎県"},
  {pic_no:45, region_no: 2, pref_name: "大分県"},
  {pic_no:46, region_no: 2, pref_name: "佐賀県"},
  {pic_no:47, region_no: 2, pref_name: "沖縄県"}
]

Pref.create(prefs)