Pref.connection.execute("TRUNCATE TABLE prefs;")
# 追加するデータを記載する
prefs = [
  {region_no: 1, pref_name: "北海道"},
  {region_no: 1, pref_name: "青森県"},
  {region_no: 1, pref_name: "秋田県"},
  {region_no: 1, pref_name: "岩手県"},
  {region_no: 1, pref_name: "山形県"},
  {region_no: 1, pref_name: "宮城県"},
  {region_no: 1, pref_name: "福島県"},
  {region_no: 1, pref_name: "千葉県"},
  {region_no: 1, pref_name: "埼玉県"},
  {region_no: 1, pref_name: "群馬県"},
  {region_no: 1, pref_name: "栃木県"},
  {region_no: 1, pref_name: "茨城県"},
  {region_no: 1, pref_name: "神奈川県"},
  {region_no: 1, pref_name: "東京都"},
  {region_no: 1, pref_name: "山梨県"},
  {region_no: 1, pref_name: "長野県"},
  {region_no: 1, pref_name: "新潟県"},
  {region_no: 1, pref_name: "富山県"},
  {region_no: 1, pref_name: "石川県"},
  {region_no: 1, pref_name: "福井県"},
  {region_no: 1, pref_name: "静岡県"},
  {region_no: 1, pref_name: "愛知県"},
  {region_no: 1, pref_name: "三重県"},
  {region_no: 1, pref_name: "岐阜県"},
  {region_no: 2, pref_name: "大阪府"},
  {region_no: 2, pref_name: "京都府"},
  {region_no: 2, pref_name: "奈良県"},
  {region_no: 2, pref_name: "兵庫県"},
  {region_no: 2, pref_name: "滋賀県"},
  {region_no: 2, pref_name: "和歌山県"},
  {region_no: 2, pref_name: "鳥取県"},
  {region_no: 2, pref_name: "岡山県"},
  {region_no: 2, pref_name: "島根県"},
  {region_no: 2, pref_name: "広島県"},
  {region_no: 2, pref_name: "山口県"},
  {region_no: 2, pref_name: "愛媛県"},
  {region_no: 2, pref_name: "香川県"},
  {region_no: 2, pref_name: "高知県"},
  {region_no: 2, pref_name: "徳島県"},
  {region_no: 2, pref_name: "福岡県"},
  {region_no: 2, pref_name: "鹿児島県"},
  {region_no: 2, pref_name: "熊本県"},
  {region_no: 2, pref_name: "宮崎県"},
  {region_no: 2, pref_name: "長崎県"},
  {region_no: 2, pref_name: "大分県"},
  {region_no: 2, pref_name: "佐賀県"},
  {region_no: 2, pref_name: "沖縄県"}
]

Pref.create(prefs)